-- MySQL Script generated by MySQL Workbench
-- 01/08/15 11:54:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `teste` ;

-- -----------------------------------------------------
-- Table `teste`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `estadocivil` VARCHAR(20) NULL,
  `endereco` VARCHAR(70) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(20) NULL,
  `uf` VARCHAR(3) NULL,
  `fone1` VARCHAR(20) NULL,
  `fone2` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `obs` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`processo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`processo` (
  `numero` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NULL,
  `vara` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `data_audiencia` DATETIME NULL,
  `data_pericia` DATETIME NULL,
  `pendencia_doc` TINYINT(1) NULL,
  `osb_pendencia` VARCHAR(45) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_processo_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_processo_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `teste`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `user` VARCHAR(45) NULL,
  `senha` VARCHAR(60) NULL,
  `admin` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste`.`log` (
  `id` INT NOT NULL,
  `data_evento` DATETIME NULL,
  `descricao` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_log_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `teste`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
